chore: replace * with Data.Kind.Type
Avoid this warning:
src/Database/Selda/FieldSelectors.hs:93:33: error: [GHC-39567] [-Wstar-is-type, Werror=star-is-type]
    Using ‘*’ (or its Unicode variant) to mean ‘Data.Kind.Type’
    relies on the StarIsType extension, which will become
    deprecated in the future.
    Suggested fix: Use ‘Type’ from ‘Data.Kind’ instead.
   |
93 | class GRSel (s :: Symbol) (f :: * -> *) where