enable TypeOperators where needed to avoid
src/Database/Selda/Prepared.hs:75:39: error: [GHC-58520] [-Wtype-equality-requires-operators, Werror=type-equality-requires-operators]
    The use of ‘~’ without TypeOperators
    will become an error in a future GHC release.
    Suggested fix: Perhaps you intended to use TypeOperators
   |
75 | instance (Typeable a, MonadSelda m, a ~ Res (ResultT q), Result (ResultT q)) =>